export const getDefaultDatasets = (
  sd3Neg,
  sd2Neg,
  sd1Neg,
  sd0,
  sd1Pos,
  sd2Pos,
  sd3Pos
) => {
  return [
    {
      label: '+3SD',
      borderColor: '#000000',
      backgroundColor: '#000000',
      data: sd3Neg,
      borderWidth: 2.5,
      pointRadius: 0,
      cubicInterpolationMode: 'monotone',
      borderJoinStyle: 'round',
    },
    {
      label: '+2SD',
      borderColor: '#F44336',
      backgroundColor: '#F44336',
      data: sd2Neg,
      borderWidth: 2.5,
      pointRadius: 0,
      cubicInterpolationMode: 'monotone',
      borderJoinStyle: 'round',
    },
    {
      label: '+1SD',
      borderColor: '#FBC02D',
      backgroundColor: '#FBC02D',
      data: sd1Neg,
      borderWidth: 2.5,
      pointRadius: 0,
      cubicInterpolationMode: 'monotone',
      borderJoinStyle: 'round',
    },
    {
      label: 'Median',
      backgroundColor: '#4CAF50',
      borderColor: '#4CAF50',
      data: sd0,
      borderWidth: 2.5,
      pointRadius: 0,
      cubicInterpolationMode: 'monotone',
      borderJoinStyle: 'round',
    },
    {
      label: '-1SD',
      borderColor: '#FBC02D',
      backgroundColor: '#FBC02D',
      data: sd1Pos,
      borderWidth: 2.5,
      pointRadius: 0,
      cubicInterpolationMode: 'monotone',
      borderJoinStyle: 'round',
    },
    {
      label: '-2SD',
      borderColor: '#F44336',
      backgroundColor: '#F44336',
      data: sd2Pos,
      borderWidth: 2.5,
      pointRadius: 0,
      cubicInterpolationMode: 'monotone',
      borderJoinStyle: 'round',
    },
    {
      label: '-3SD',
      borderColor: '#000000',
      backgroundColor: '#000000',
      data: sd3Pos,
      borderWidth: 2.5,
      pointRadius: 0,
      cubicInterpolationMode: 'monotone',
      borderJoinStyle: 'round',
    },
  ]
}
